# docker-compose.yml
services:
  publisher:
    build: .
    environment:
      RABBITMQ_HOST: "192.168.2.68"
      RABBITMQ_QUEUE: "project_queue"
    volumes:
      - ./projects.json:/app/projects.json
