# docker-compose.yml
services:
  publisher:
    build: .
    environment:
      RABBITMQ_HOST: "${RABBITMQ_HOST_IP}"
      RABBITMQ_QUEUE: "${RABBITMQ_DEFAULT_QUEUE}"
    volumes:
      - ./projects.json:/app/projects.json
