# worker-stack.yaml
services:
  worker:
    image: fredrikforsman15/de2:v2 
    environment:
      RABBITMQ_HOST: "192.168.2.97"    # IP RabbitMQ Broker VM
      RABBITMQ_QUEUE: "project_queue"
    volumes:
      - test_summary:/summary  # Mount the NFS volume
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 2

volumes:
  test_summary:   # Volume for the results
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.97,rw" 
      device: ":/home/ubuntu/exports/test_summary" # Export path to the NFS server
